### PR TITLE
Replace DimitrijeDragasevic with LudiSistemas

### PR DESCRIPTION
**Pull request by brdji**
A new team member will be joining us to contribute on Testground.

### CODE REVIEW

**Review by galargh — APPROVED** [review]
Approving since Darko takes care of the Bloxico team setup.

**Comment by galargh** [comment]
Something's off with GitHub Actions - I'll try to investigate why the plan didn't run.

**Comment by galargh** [comment]
Ahhh, I was a bit too hasty to approve. 

> This branch has conflicts that must be resolved

Your fork is out of date.

FYI, since you first created your fork we changed how the configuration is stored from multi JSON to single YAML.

So now, to introduce this change you'll have to modify a single file:
- here https://github.com/testground/github-mgmt/blob/master/github/testground.yml#L14
- and here https://github.com/testground/github-mgmt/blob/master/github/testground.yml#L192

**Comment by brdji** [comment]
Got it, thanks! I'll refresh this fork and fix the PR.

**Review by galargh — APPROVED** [review]

**Pull request merged**
